[build]
  command = "npm run build"
  publish = "dist"

# Removed: [dev] section, reverting to Netlify CLI's default behavior
# [dev]
#   command = "npm run dev"
#   port = 8888
#   targetPort = 32100
#   publish = "dist"
#   framework = "#vite"