[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.environment]
  NETLIFY_BLOBS_SITE_ID = "1096a290-2d0c-4d03-846f-9eebbce52f52"
  NETLIFY_BLOBS_TOKEN = "nfp_sKWK5zFa35g4eyF6vqxLQ744wt42YC726a29"