[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Ensure @netlify/blobs is bundled correctly
  external_node_modules = ["@netlify/blobs"]
  # Use esbuild for faster function bundling
  node_bundler = "esbuild"
  # Explicitly expose environment variables to functions
  [functions.environment]
    NETLIFY_SITE_ID = "${NETLIFY_SITE_ID}"
    NETLIFY_API_TOKEN = "${NETLIFY_API_TOKEN}"