[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 32100 # Match the Vite server port
  port = 8888 # Default Netlify Dev port

[[redirects]]
  from = "/.netlify/images"
  to = "/.netlify/images/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200