[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev" # Command to start your Vite dev server
  port = 8888             # Port Netlify CLI will run on
  targetPort = 32100      # Port your Vite dev server runs on
  publish = "dist"        # Directory to serve static assets from
  framework = "#vite"     # Explicitly tell Netlify CLI it's a Vite project