[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # Explicitly expose environment variables for Netlify Blobs
  [functions.environment]
    NETLIFY_BLOBS_SITE_ID = "${NETLIFY_SITE_ID}"
    NETLIFY_BLOBS_TOKEN = "${NETLIFY_API_TOKEN}"