import { Database } from './database.types'; // Assuming database.types.ts is generated by Supabase CLI

// Utility type to extract Row, Insert, or Update types from a Supabase table
export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database['public']['Tables'] & Database['public']['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database['public']['Tables'] &
        Database['public']['Views'])
    ? (Database['public']['Tables'] &
        Database['public']['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
    : never
    : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database['public']['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database['public']['Tables']
    ? Database['public']['Tables'][PublicTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database['public']['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database['public']['Tables']
    ? Database['public']['Tables'][PublicTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

// 1. Core Row Types
export type AlertRow = Tables<'alerts'>['Row'];
export type AppSettingsRow = Tables<'app_settings'>['Row'];
export type AppSettingsHistoryRow = Tables<'app_settings_history'>['Row'];
export type CommentRow = Tables<'comments'>['Row'];
export type ContactSettingsRow = Tables<'contact_settings'>['Row'];
export type FeedbackRow = Tables<'feedback_and_suggestions'>['Row'];
export type IncidentRow = Tables<'incidents'>['Row'];
export type LikeRow = Tables<'likes'>['Row'];
export type ProfileRow = Tables<'profiles'>['Row'];
export type NotificationSettingsRow = Tables<'user_notification_settings'>['Row'];

// 2. Insert / Update Types
export type AlertInsert = TablesInsert<'alerts'>;
export type AlertUpdate = TablesUpdate<'alerts'>;

export type AppSettingsInsert = TablesInsert<'app_settings'>;
export type AppSettingsUpdate = TablesUpdate<'app_settings'>;

export type AppSettingsHistoryInsert = TablesInsert<'app_settings_history'>;
export type AppSettingsHistoryUpdate = TablesUpdate<'app_settings_history'>;

export type CommentInsert = TablesInsert<'comments'>;
export type CommentUpdate = TablesUpdate<'comments'>;

export type ContactSettingsInsert = TablesInsert<'contact_settings'>;
export type ContactSettingsUpdate = TablesUpdate<'contact_settings'>;

export type FeedbackInsert = TablesInsert<'feedback_and_suggestions'>;
export type FeedbackUpdate = TablesUpdate<'feedback_and_suggestions'>;

export type IncidentInsert = TablesInsert<'incidents'>;
export type IncidentUpdate = TablesUpdate<'incidents'>;

export type LikeInsert = TablesInsert<'likes'>;
export type LikeUpdate = TablesUpdate<'likes'>;

export type ProfileInsert = TablesInsert<'profiles'>;
export type ProfileUpdate = TablesUpdate<'profiles'>;

export type NotificationSettingsInsert = TablesInsert<'user_notification_settings'>;
export type NotificationSettingsUpdate = TablesUpdate<'user_notification_settings'>;

// 3. Handy Utility Types
// a) Pick only the columns you need for a query
export type IncidentListItem = Pick<IncidentRow,
  'id' | 'title' | 'type' | 'date' | 'latitude' | 'longitude' | 'image_url' | 'description' | 'location' | 'admin_id' | 'created_at'
>;

// b) Make a column required (useful for inserts)
export type RequiredInsert<T> = { [P in keyof T]-?: NonNullable<T[P]> };

// Example: NewIncident type for creating an incident (excluding auto-generated fields)
export type NewIncident = RequiredInsert<Omit<IncidentInsert, 'id' | 'created_at' | 'search_vector' | 'date'>>;
export type NewAlert = RequiredInsert<Omit<AlertInsert, 'id' | 'created_at'>>;
export type NewComment = RequiredInsert<Omit<CommentInsert, 'id' | 'created_at'>>;

// c) JSON payload helpers (layout, contact_cards, push_subscription …)
export type LayoutJson = AppSettingsRow['layout'];
export type ContactCardsJson = ContactSettingsRow['contact_cards'];
export type PushSubJson = NotificationSettingsRow['push_subscription'];

// Custom types for joined data
export type CommentWithProfile = CommentRow & {
  profiles: Pick<ProfileRow, 'username' | 'avatar_url'> | null;
};

export type FeedbackWithProfile = FeedbackRow & {
  profiles: Array<Pick<ProfileRow, 'username' | 'id'>> | null;
};

// Custom type for ContactCard (since it's an array of objects within ContactSettingsRow)
export type ContactCard = ContactCardsJson extends (infer U)[] ? U : never;