import { precacheAndRoute, cleanupOutdatedCaches, clientsClaim } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<any> };

// Access environment variable directly
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

// This is the precache manifest generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Claim clients immediately
clientsClaim();
self.skipWaiting();

// Runtime caching routes (copied from existing vite.config.ts)
registerRoute(
  ({ url }: { url: URL }) => url.origin === self.location.origin,
  new NetworkFirst({
    cacheName: 'static-assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 7,
      }),
    ],
  }),
  'GET'
);

// Supabase incidents API cache
registerRoute(
  new RegExp(`^${SUPABASE_URL}/rest/v1/incidents`),
  new StaleWhileRevalidate({
    cacheName: 'supabase-incidents-api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  }),
  'GET'
);

// Supabase incident images cache
registerRoute(
  new RegExp(`^${SUPABASE_URL}/storage/v1/object/public/incident_images/`),
  new CacheFirst({
    cacheName: 'supabase-incident-images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30,
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  }),
  'GET'
);

// --- Custom Push Notification Handler ---
self.addEventListener('push', (event: PushEvent) => {
  console.log('[Service Worker] Push Received.');
  const data = event.data?.json() ?? {};
  const title = data.title ?? 'New Notification';
  const options = {
    body: data.body ?? 'You have a new message.',
    icon: data.icon ?? '/Logo.png',
    badge: data.badge ?? '/Logo.png',
    data: data.data, // Pass custom data like URL
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[Service Worker] Notification click received.', event.notification.data);
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/'; // Default to home page

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: readonly WindowClient[]) => {
      for (const client of clientList) {
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
      return null;
    })
  );
});